### PR TITLE
Add the "arc" feature-gate.

### PR DESCRIPTION
**Pull request by phaazon**
0.11.2

### CODE REVIEW

**Comment by phaazon** [comment]
Ping @Icefoxen, do you think it solves your issue? :)

**Comment by phaazon** [comment]
Sure, tell me if it’s okay, then I will merge it so that it ends up on crates.io.

**Comment by icefoxen** [comment]
Appears to work perfectly.  Thank you so much!

**Comment by phaazon** [comment]
Great, pleased you like it! I’ll be merging it right away then! I’ll upload the new version as soon as possible (I’m not sure I have enough privileges on that computer to upload to crates.io).

Thanks for the feedback!

**Pull request merged**
